### ISSUE TITLE
Item level?

### ISSUE THREAD

**Issue by MarkPearce** [Drental/shopping-experience#2]
feature request.

it would be cool to see item level, either as a column on the main table (ideal) or on item description.

**Comment by Drental** [comment]
that's a feature request that should go to https://gitlab.com/hooking/foundry-vtt---pathfinder-2e/-/issues
I am not changing the vendor sheet here after all so the module doesn't break.

in general the Items are 0-2 levels lower than the merchant with the exception of their specialty, that they offer up to one level above their own.
