### ISSUE TITLE
Naming Convention Issues.

### ISSUE THREAD

**Issue by keithkb5** [Drental/shopping-experience#3]
Four issues were found that had to do with naming conventions.

![Foundry-Shopping Experience Warnings](https://user-images.githubusercontent.com/3419384/216766805-61f2d598-461a-4de3-be37-3bd3f0083523.png)

**Comment by Drental** [comment]
putting a pin in this and will try to resolve it when I do an update after treasure vault releases.

**Comment by keithkb5** [comment]
Thank you.  Glad to see you're still on it.  Is there a way to pick what goes into the store or is it just an auto fill?  I know projects can get 'request heavy' so please don't take it wrong.

**Comment by Drental** [comment]
It's all hand built.
