### ISSUE TITLE
Shops stock Uncommon and Unique items

### ISSUE THREAD

**Issue by dmpunks** [Drental/shopping-experience#8]
Excellent time saving module but there are a couple of errors for the items included as inventory in the Otari Shops compendium.

- Blades for Glades & Otari Garrison both sell Clan Daggers. These are Uncommon items that are sort of important to dwarves. This really shouldn't be for sale, not even if the seller was a dwarf.
- Stone Ring Pond is selling the Hunter's Brooch. This is a Unique item available in the Hands of the Devil adventures (part of Abomination Vaults). It should only be available from the town mayor as it is a valuable heirloom.
- There's a lot of Uncommon items for sale inclyding Katars, Daggers of Eternal Sleep and the scroll of Sudden Bolt among the rest of the shops. Unlike the two items mentioned earlier, I could definitely see a reason for them being sold by those shops, though I believe GMs installing this module should receive a heads-up at least.

**Comment by LumberKing** [comment]
> Excellent time saving module but there are a couple of errors for the items included as inventory in the Otari Shops compendium.
> 
> * Blades for Glades & Otari Garrison both sell Clan Daggers. These are Uncommon items that are sort of important to dwarves. This really shouldn't be for sale, not even if the seller was a dwarf.
> * Stone Ring Pond is selling the Hunter's Brooch. This is a Unique item available in the Hands of the Devil adventures (part of Abomination Vaults). It should only be available from the town mayor as it is a valuable heirloom.
> * There's a lot of Uncommon items for sale inclyding Katars, Daggers of Eternal Sleep and the scroll of Sudden Bolt among the rest of the shops. Unlike the two items mentioned earlier, I could definitely see a reason for them being sold by those shops, though I believe GMs installing this module should receive a heads-up at least.

Also to add to this, some of the items are higher level than the shop or even the town itself.

**Comment by dmpunks** [comment]
Oooh, I haven't really noticed that. Otari's settlement ability does allow shops to sell up to Level 10 consumables, but only consumables.

**Comment by Drental** [comment]
I don't really touch the Otari shops, they are a freebie I got from a friend ^^;

I've added some scripts to make editing the module more reasonable, feel free to make a PR or give me a list with the changes you want me to do.
